hints:
  - title_markdown: "How do I read the user's command?"
    body_markdown: |-
      Use Python's [`input()`](https://docs.python.org/3/library/functions.html#input) function to capture the command the user types in:

      ```python
      # Capture the user's command in the "command" variable
      command = input()
      ```

      The `input()` function waits for the user to enter a command and then returns it as a string.

  - title_markdown: "How do I print the command not found message?"
    body_markdown: |-
      Use Python's [print()](https://docs.python.org/3/library/functions.html#print) function to print the `<command>: command not found` message:

      ```python
      # Prints the "<command>: command not found" message
      print(f"{command}: command not found")
      ```

      The `print()` function prints a string to the console. The above code uses a [f-string](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals) to include the command in the message.
